version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "2343:80"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gogs-jenkins-network
    depends_on:
      - gogs
      - jenkins

  gogs:
    image: gogs/gogs:latest
    container_name: gogs
    ports:
      - "13000:3000"
      - "122:22"  # Git SSH port
    volumes:
      - ./data/gogs:/data
    # envfile
    environment:
      - GOGS_CUSTOM=/data/gogs
    networks:
      - gogs-jenkins-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "18080:8080"
    # env_file:
      # - cargo.env
    environment:
      # - PATH="/root/.cargo/bin:$PATH"
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - ./data/jenkins:/var/jenkins_home
    networks:
      - gogs-jenkins-network
    depends_on:
      - gogs

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - gogs-jenkins-network

  ssh-agent:
      image: debian:latest
      container_name: ssh-agent
      ports:
      - "123:22"
      working_dir: /app

      volumes:
        - ./data/testing:/app  # Mount a volume for your testing code/scripts
      networks:
        - gogs-jenkins-network
      depends_on:
        - postgres
      command: tail -f /dev/null  # Keeps the container running for testing purposes




networks:
  gogs-jenkins-network:
