@startuml "Deploy diagram"

node pc as "Client"{

}

node dc as "Docker-compose" {

    node psql_node as "Postgress" {
        database psql as "postgress"
    }

    node gogs_node as "Gogs" {
        agent gogs as "gogs"
    }
    node jenkins_node as "Jenkins" {
        agent jenkins as "jenkins"
    }
    
    node nginx_node as "NGINX" {
        agent nginx as "nginx"
    }

    node debian_node as "Debian"{
        agent ssh as "sshd"
    }

    gogs -(0- psql : "psql"

    jenkins -(0- gogs : "http"
    jenkins -(0- gogs : "ssh"
    jenkins -(0 ssh : "ssh"

    nginx -(0- jenkins : "http"
    nginx -(0- gogs : "http"
    
    pc -(0 nginx : "https"

}


@enduml